Repository openwhyd/openwhyd, pull requests merged in 2018-09, with the labels that each got.

#134 Test build on Node 8 LTS
  .travis.yml
  whydJS/package-lock.json
Labels: enhancement, help wanted

#160 fix(scripts): Fix and clean-up production scripts => v1.2.2
  .gitignore
  Makefile
  scripts/restart.sh
  scripts/start.sh
  whydJS/package-lock.json
  whydJS/package.json
Labels: enhancement

#161 fix(profile): fix playlist re-ordering
  whydJS/public/js/feed-trackorder.js
Labels: bug

#167 chore(versioning): fix semantic-release integration
  whydJS/package-lock.json
  whydJS/package.json
Labels: enhancement
