Repository openwhyd/openwhyd, pull requests merged in 2019-11, with the labels that each got.

#248 feat(maintenance): restart script generates nginx config from template
  config/nginx-site-template
  scripts/restart.sh
Labels: production

#249 feat(security): add rate limiting to POST requests
  config/nginx-site-template
  scripts/restart.sh
Labels: security / privacy

#250 test(auth): refacto authentication test suite
  test/api/auth.api.tests.js
Labels: enhancement

#251 fix(tests): homogenize returns of api client
  test/api-client.js
  test/api/auth.api.tests.js
  test/api/post.api.tests.js
  test/api/user.api.tests.js
Labels: enhancement

#252 feat(security): use argon2 to hash user password on sign up + tests
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/openwhyd.iml
  .idea/vcs.xml
  app/controllers/private/register.js
  package-lock.json
  test/api/auth.api.tests.js
  test/unit/argon2-tests.js
Labels: security / privacy
