Repository openwhyd/openwhyd, pull requests merged in 2020-09, with the labels that each got.

#350 fix(css): Remove obsolete CSS definitions
  public/css/common.css
Labels: enhancement, feedback wanted

#358 fix(e2e-tests): Finish migration from Webdriver to Cypress
  .circleci/config.yml
  .github/workflows/nodejs.yml
  cypress.json
  cypress/integration/acceptance.spec.ts
  cypress/integration/bookmarklet.spec.ts
  cypress/integration/stream.spec.ts
  cypress/integration/upload.spec.ts
  cypress/plugins/cy-ts-preprocessor.js
  cypress/plugins/index.js
  docs/INSTALL.md
  package-lock.json
  package.json
  test/acceptance-cmds.js
  test/specs/upload.tests.js
  test/unit/unit-tests.js
  test/web-ui.js
  wdio.conf.js
Labels: enhancement

#360 fix(deps): Update dependencies
  Dockerfile
  app.js
  package-lock.json
  package.json
Labels: dependencies, security / privacy

#361 fix(logs): Re-import colors package, to prevent "undefined" entries in logs
  app.js
Labels: bug

#362 fix(tests): Test avatar upload
  .github/workflows/docker.yml
  cypress.json
  cypress/fixtures/upload-resources/sample-avatar.jpg
  cypress/fixtures/upload-resources/sample-banner.jpg
  cypress/fixtures/upload-resources/sample-banner.png
  cypress/integration/upload.spec.ts
  cypress/plugins/index.js
  cypress/plugins/index.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  cypress/support/index.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#363 fix(logs): Reduce amount of logging in production
  app/controllers/admin/invites.js
  app/controllers/collabPl.js
  app/controllers/pgApp.js
  app/controllers/pgGenre.js
  app/controllers/recentActivity.js
  app/controllers/userLibrary.js
  app/models/analytics.js
  app/models/searchMongo.js
  app/models/track.js
  app/models/user.js
  app/templates/mainTemplate.js
  scripts/start.sh
Labels: production

#364 feat: ⚰️ Bury collaborative playlists (never-finished feature)
  app/controllers/api/post.js
  app/controllers/collabPl.js
  app/models/collabPl.js
  app/models/post.js
  app/templates/collabPl.html
  app/templates/dlgPlContributors.html
  app/templates/feed.html
  app/templates/posts.js
  app/templates/userProfileV2.html
  config/app.route
  config/initdb.js
  public/css/browse.css
  public/js/collabPl.js
  public/js/postBoxV2.js
Labels: enhancement

#365 fix(logs): Remove or clarify old production + unit test logs
  app/controllers/admin/tests/playlist.js
  app/controllers/admin/tests/stream.js
  app/controllers/admin/tests/user.js
  app/controllers/api/follow.js
  app/controllers/private/contentType.js
  app/lib/get/index.js
  app/models/email.js
  app/models/emailFake.js
  app/models/logging.js
  app/models/mongodb-shell-runner.js
  app/models/notif.js
  app/models/notifEmails.js
  app/models/search.js
  app/models/searchAlgolia.js
  app/models/track.js
  app/models/user.js
  app/serverTestRunner.js
  app/templates/invitePage.html
  config/initdb.js
  scripts/data-analysis-scripts/src/json-helpers/run-mongo-script-from-json-dump.js
  test/unit/notif-tests.js
Labels: enhancement

#366 fix(tests): Modernize unit tests of Notifications
  app/models/notif.js
  test/unit/notif-tests.js
Labels: enhancement

#367 fix(linter): Re-enable linting of JS files in VSCode
  .eslintrc.json
  tsconfig.json
Labels: enhancement

#354 docs: Add project structure to CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: enhancement
