Repository openwhyd/openwhyd, pull requests merged in 2020-03, with the labels that each got.

#268 fix(#262): specify dedicated YouTube API key for postEditV2
  app/templates/postEditV2.html
Labels: bug

#271 fix(#262): specify dedicated YouTube API key for mainTemplate
  app/templates/mainTemplate.js
Labels: bug

#270 fix(#269): invalid template caused crash when adding from bookmarklet
  app/templates/postEditV2.html
Labels: bug

#269 fix(refact): extract "sidebox" announcements into dedicated template
  app/templates/feed.html
  app/templates/feed.js
  app/templates/sideBox.html
Labels: enhancement

#272 feat(sideBox): inform about YouTube issues
  app/templates/sideBox.html
Labels: enhancement

#274 fix(ci): execution of Cypress test on GitHub Actions workflow
  .github/workflows/nodejs.yml
Labels: bug

#275 feat(ci): speed up docker image creation
  Dockerfile
  package.json
Labels: enhancement

#277 fix(#262): extend youtube api quota from bookmarklet
  public/js/bookmarklet.js
  test/specs/bookmarklet.tests.js
Labels: bug

#278 fix(#262): disable external track search (incl. YouTube)
  app/templates/searchPage.html
  public/css/common.css
  public/images/SearchIconFilterHover.png
  public/images/SearchIconFilterValidated.png
  public/images/icon-whyd.png
  public/js/searchPage.js
  public/js/whyd.js
Labels: bug

#279 fix(#262): bookmarklet to not fetch youtube metadata
  public/js/bookmarklet.js
Labels: bug

#280 refactor: add unit tests for bookmarklet
  public/js/bookmarklet.js
  test/unit/bookmarklet-tests.js
Labels: enhancement

#281 fix(bookmarklet): refactor bookmarklet and add tests for #262
  public/js/bookmarklet.js
  test/unit/bookmarklet-tests.js
Labels: enhancement

#282 fix(bookmarklet): display playable results hits first
  public/js/bookmarklet.js
Labels: bug

#283 fix(youtube): regroup api keys in same project, for #262
  app/templates/mainTemplate.js
  app/templates/postEditV2.html
Labels: bug

#284 fix(youtube): dedicated api key for development
  app/templates/postEditV2.html
Labels: bug

#285 feat(bookmarklet): extract youtube track names from page
  public/js/bookmarklet.js
  test/unit/bookmarklet-tests.js
Labels: enhancement

#286 fix(bookmarklet): [refactor] move browser-only code to end
  public/js/bookmarklet.js
Labels: enhancement

#289 fix(ui): simplify bookmarklet page and homogenize wording
  app/templates/feed.html
  app/templates/onboarding.html
  app/templates/onboarding/bookmarklet.html
  misc/BrowserExt/Chrome.crx
  misc/BrowserExt/Chrome.pem
  misc/BrowserExt/Chrome.zip
  misc/BrowserExt/Chrome/manifest.json
Labels: enhancement

#290 fix(bookmarklet): fix and homogenize wording, second pass
  app/templates/feed.html
  app/templates/onboarding.html
  app/templates/onboarding/bookmarklet-old.html
  app/templates/onboarding/bookmarklet.html
Labels: bug

#288 fix(#262): announce improvements on home page
  app/templates/sideBox.html
Labels: enhancement

#287 fix(bookmarklet): refactor makeFileDetector() and make it more robust
  public/js/bookmarklet.js
  test/unit/bookmarklet-tests.js
Labels: enhancement

#276 feat(tests): migrate bookmarklet e2e test to Cypress
  cypress.json
  cypress/fixtures/example.json
  cypress/fixtures/users.js
  cypress/integration/bookmarklet.spec.js
  cypress/integration/examples/_openwhyd.spec.js
  package-lock.json
  package.json
  public/html/test-resources/youtube-videos.html
Labels: enhancement

#260 fix(ui): never-ending loading animation on empty search
  public/js/quickSearch.js
  public/js/searchPage.js
Labels: bug

#293 fix(ui): Hidden logo on search bug
  public/js/whyd.js
Labels: bug

#298 feat(ci): separate ci tasks for each type of tests
  .circleci/config.yml
  .github/workflows/nodejs.yml
  package.json
Labels: enhancement, production

#299 test(#295): add non-regression test for pagination
  app.js
  config/initdb_team.js
  config/initdb_testing.js
  cypress/fixtures/users.js
  cypress/integration/acceptance.spec.ts
  cypress/integration/bookmarklet.spec.ts
  cypress/integration/stream.spec.ts
  cypress/support/commands.js
  cypress/support/index.d.ts
  docs/INSTALL.md
  test/reset-test-db.js
Labels: bug

#296 fix(error): 404 redirect when clicking load more on account stream
  app/templates/feed.html
Labels: bug

#294 fix(ui): Display correct track error message when using electron app
  public/js/whydPlayer.js
Labels: bug

#302 fix(tests): Reset database between each Cypress tests
  .circleci/config.yml
  .github/workflows/nodejs.yml
  app.js
  app/controllers/testing/reset.js
  app/models/logging.js
  app/models/mongodb.js
  config/app.route
  cypress/integration/stream.spec.ts
  cypress/support/commands.js
  cypress/support/index.d.ts
  cypress/support/index.js
  package.json
Labels: enhancement

#304 fix(tests): Create dummy posts from Cypress tests instead of from db init
  config/initdb_testing.js
  cypress/integration/stream.spec.ts
  cypress/support/commands.js
  cypress/support/index.d.ts
Labels: enhancement

#301 fix(ci): Migrate acceptance tests from Webdriver to Cypress
  config/initdb_testing.js
  cypress/integration/acceptance.spec.ts
  cypress/integration/bookmarklet.spec.ts
  cypress/support/commands.js
  cypress/support/index.js
  test/specs/acceptance.tests.js
Labels: enhancement

#303 fix(bug): resizing the pages scrolls to the top
  public/css/common.css
  public/js/whyd.js
Labels: bug

#305 feat(logs): Simplify logging to stdout and stderr
  app.js
Labels: enhancement

#308 feat(ci): run CI tests with docker-compose
  .github/workflows/docker.yml
Labels: enhancement

#306 feat(ci): Add version as tag, when publishing on Docker Hub
  .github/workflows/nodejs.yml
Labels: enhancement

#311 fix(docker): ignore log files
  .dockerignore
Labels: enhancement

#313 fix(deps): remove forever from dependencies
  docs/INSTALL.md
  package-lock.json
  package.json
  scripts/restart.sh
Labels: enhancement

#314 fix(deps): upgrade to (smaller) playemjs v0.3.1
  package-lock.json
  package.json
  public/js/playem-all.js
  public/js/playem-min.js
Labels: dependencies

#315 fix(prod): use latest version of forever in prod scripts
  package.json
  scripts/restart.sh
Labels: bug, production

#312 fix(docker): use slim node docker image
  Dockerfile
  package-lock.json
  package.json
  public/js/playem-all.js
  public/js/playem-min.js
Labels: enhancement

#317 feat(deps): upgrade playemjs to get rid of flash/swfobject
  package-lock.json
  package.json
  public/js/playem-all.js
  public/js/playem-min.js
Labels: enhancement
