Repository openwhyd/openwhyd, pull requests merged in 2020-11, with the labels that each got.

#374 fix(tests): Workaround "quota exceeded" errors from YouTube API
  cypress/integration/acceptance.spec.ts
  cypress/support/commands.ts
  package-lock.json
  package.json
  public/js/playem-all.js
  public/js/playem-min.js
Labels: bug

#373 fix(importer): Fix navigation and login after importing user data locally
  app/controllers/testing/refresh.js
  docs/INSTALL.md
  scripts/import-from-prod.js
Labels: enhancement

#375 fix(deps): Clean-up dependencies
  app/models/recom.js
  package-lock.json
  package.json
Labels: enhancement

#376 fix(deps): Update kramdown dependency
  docs/Gemfile.lock
Labels: dependencies, security / privacy

#378 feat(UI): Latest tracks on landing page
  app/controllers/LibAll.js
  app/controllers/hotTracks.js
  app/controllers/userLibrary.js
  app/templates/feed.html
  app/templates/logging.js
  app/templates/mainTemplate.js
  app/templates/sideBox.html
  public/css/common.css
  public/css/pgCity-common.css
  public/html/landingOpen.html
  public/images/icon-navbar-applestore.png
  public/js/whyd.js
Labels: enhancement

#380 fix: Remove Barelog / Productfeed
  app/templates/feed.html
Labels: enhancement

#382 fix(379): Load templates synchronously, to prevent crash on CI
  app/templates/templateLoader.js
Labels: bug

#377 fix(bookmarklet): Detect cover art from Bandcamp page
  cypress/integration/bookmarklet.spec.ts
  public/js/bookmarklet.js
Labels: bug

#383 fix(docker): Make Docker build faster
  Dockerfile
  app/lib/my-http-wrapper/http/Application.js
Labels: enhancement

#384 fix(bookmarklet): Split bookmarklet.js into separate TypeScript files
  docs/CONTRIBUTING.md
  package.json
  public/js/bookmarklet.js
  public/js/bookmarklet.ts
  public/js/bookmarkletLogic.ts
  public/js/bookmarkletUI.ts
  public/js/bookmarkletYouTube.ts
  scripts/transpile-bookmarklet.sh
  test/unit/bookmarklet-tests.js
Labels: enhancement

#385 fix: Hotfixes
  app/templates/feed.html
  public/js/bookmarklet.js
  public/js/bookmarkletLogic.ts
Labels: bug

#386 fix: Remove slow routes
  app/controllers/LibStyle.js
  app/controllers/pgApp.js
  app/controllers/pgGenre.js
  app/controllers/userLibrary.js
  app/templates/pgGenre.html
  config/app.route
Labels: bug, enhancement

#387 feat: Remove Discover page + suggested users
  app/controllers/LibFriends.js
  app/controllers/discover.js
  app/controllers/recentActivity.js
  app/templates/discover.html
  app/templates/discover/trending.html
  app/templates/feed.html
  app/templates/feed.js
  app/templates/recentActivity.html
  config/app.route
  config/initdb.js
  public/css/common.css
  public/images/back-boo.png
  public/images/icon-clock-small.png
  public/images/icon-ranking-first.png
  public/images/icon-ranking-nbAdds.png
  public/images/icon-ranking-nbLikes.png
  public/images/icon-ranking-nbPlays.png
  public/images/icon-ranking-nbSubscribers.png
  public/images/icon-ranking-second.png
  public/images/icon-ranking-third.png
  public/images/pointe-activetab-discover.png
  public/js/discover.js
  public/js/feed-rightbar.js
Labels: enhancement

#388 feat: Remove "Playlist Contest"
  app.js
  app/controllers/LibFriends.js
  app/controllers/LibUser.js
  app/controllers/playlistcontest.js
  app/controllers/private/register.js
  app/models/plContest.js
  app/templates/feed.html
  app/templates/playlistcontest.html
  app/templates/playlistcontest.js
  app/templates/userPlaylistV2.html
  config/app.route
  config/initdb.js
  public/css/common.css
  public/images/email-contest-head.jpg
  public/images/icon-contest-big.png
  public/images/icon-contest-small.png
  public/images/icon-vote.png
  public/js/feed-rightbar.js
  public/js/playlistcontest.js
Labels: enhancement

#390 feat: Remove "City" pages
  app/controllers/api/city.js
  app/data/citymembers._template_.js
  app/data/citymembers.london.js
  app/data/citymembers.madrid.js
  app/data/citymembers.paris.js
  app/templates/feed.html
  config/app.route
  public/cityData/_template_-people.js
  public/cityData/_template_-playlists.js
  public/cityData/london-people.js
  public/cityData/london-playlists.js
  public/cityData/madrid-people.js
  public/cityData/madrid-playlists.js
  public/cityData/paris-people.js
  public/cityData/paris-playlists.js
  public/cityData/template.html
  public/css/browse.css
  public/css/pgCity-common.css
  public/css/pgCity-index.css
  public/css/pgCity-people.css
  public/css/pgCity-playlists.css
  public/css/pgCity-popup.css
  public/css/pgCity-tracks.css
  public/images/london-home-button.png
  public/images/madrid-home-button.png
  public/images/paris-home-button.png
  public/images/pause-pgCity.png
  public/images/pgCity-london-background.jpg
  public/images/pgCity-london-cityname-header.png
  public/images/pgCity-london-cityname.png
  public/images/pgCity-london-fb-sharing.jpg
  public/images/pgCity-madrid-background.jpg
  public/images/pgCity-madrid-cityname-header.png
  public/images/pgCity-madrid-cityname.png
  public/images/pgCity-madrid-fb-sharing.jpg
  public/images/pgCity-paris-background.jpg
  public/images/pgCity-paris-cityname-header.png
  public/images/pgCity-paris-cityname.png
  public/images/pgCity-paris-fb-sharing.jpg
  public/images/play-pgCity.png
  public/js/jquery.ellipsis.min.js
  public/js/pgCity-common.js
  public/js/pgCity-popup.js
Labels: enhancement

#391 fix(codacy): Fix code quality issues listed by Codacy
  public/css/browse.css
  public/js/ContentEmbed.js
  public/js/TrackFinder.js
  public/js/bookmarkletdev.js
  public/js/dropzone.js
  public/js/facebook.js
  public/js/onboarding.js
  public/js/postBox.js
  public/js/postBoxV2.js
  public/js/settings.js
  public/js/ui.js
  public/js/whyd.js
  public/js/whydEmbed.js
  public/js/whydPlayer.js
  public/js/whydRemotePlayer.js
  public/js/whydtr.js
  test/api-client.js
  test/old/hypemachine.tests.js
  test/unit/email-validation-tests.js
  test/unit/unit-tests.js
Labels: enhancement

#392 fix: Various hotfixes
  app.js
  app/models/activity.js
  app/models/mongodb.js
Labels: bug, enhancement

#393 fix(bookmarklet): Extract pageDetectors and urlDetectors to separate files
  public/js/bookmarklet-README.md
  public/js/bookmarklet.js
  public/js/bookmarklet.ts
  public/js/bookmarkletLogic.ts
  public/js/bookmarkletPageDetectors.ts
  public/js/bookmarkletUI.ts
  public/js/bookmarkletUrlDetectors.ts
  public/js/bookmarkletYouTube.ts
  scripts/transpile-bookmarklet.sh
  test/unit/bookmarklet-tests.js
Labels: enhancement

#394 fix(bandcamp): Fetch the stream URL from the track's page
  app/controllers/api/bandcampExtractor.js
  app/controllers/api/contentExtractor.js
  app/lib/get/index.js
  app/lib/hypem/index.js
  app/models/metadataResolver.js
  app/templates/mainTemplate.js
  cypress/integration/playback.spec.ts
  public/js/ContentEmbed.js
  public/js/whydPlayer.js
  test/old/content-embed.tests.js
  test/unit/bandcampExtractor-tests.js
Labels: enhancement

#395 fix: Check that the API is called from our own domain
  app/controllers/api/bandcampExtractor.js
Labels: enhancement, security / privacy

#396 feat(player): Enable background playback
  app/controllers/api/contentExtractor.js
  public/js/whydPlayer.js
Labels: enhancement

#399 feat: Remove genres from onboarding and hot tracks
  app.js
  app/controllers/LibUser.js
  app/controllers/admin/plTags.js
  app/controllers/admin/tests/user.js
  app/controllers/api/playlist.js
  app/controllers/api/user.js
  app/controllers/hotTracks.js
  app/controllers/onboarding.js
  app/controllers/private/register.js
  app/models/featuredUsers.js
  app/models/plTags.js
  app/models/post.js
  app/models/track.js
  app/templates/hotTracks.html
  app/templates/notif.js
  app/templates/onboarding.html
  app/templates/posts.html
  app/templates/posts.js
  app/templates/userProfileV2.html
  cypress/integration/acceptance.spec.ts
  docs/API.md
  public/css/common.css
  public/css/onboarding.css
  public/css/userProfileV2.css
  public/images/OnboardingGenreBlues.jpg
  public/images/OnboardingGenreClassical.jpg
  public/images/OnboardingGenreElectro.jpg
  public/images/OnboardingGenreFolk.jpg
  public/images/OnboardingGenreHipHop.jpg
  public/images/OnboardingGenreIndie.jpg
  public/images/OnboardingGenreJazz.jpg
  public/images/OnboardingGenreLatin.jpg
  public/images/OnboardingGenreMetal.jpg
  public/images/OnboardingGenrePop.jpg
  public/images/OnboardingGenrePunk.jpg
  public/images/OnboardingGenreRNB.jpg
  public/images/OnboardingGenreReggae.jpg
  public/images/OnboardingGenreRock.jpg
  public/images/OnboardingGenreSoul.jpg
  public/images/OnboardingGenreWorld.jpg
  public/images/OnboardingIconGenreValidate.png
  public/images/OnboardingIconGenreValidateHover.png
  public/images/hot-tracks-genre.png
  public/js/hotTracks.js
  public/js/onboarding.js
Labels: enhancement

#400 fix(nodejs): Switch to Node.js 12
  .circleci/config.yml
  .github/workflows/nodejs.yml
  .nvmrc
  .vscode/launch.json
  Dockerfile
  Makefile
  package.json
  scripts/wait-for-http-server.sh
Labels: security / privacy

#401 fix(ui): Never-ending refresh of full stream
  app/templates/feed.html
Labels: bug

#404 fix(perf): Reduce use of synchronous IO calls
  app.js
  app/controllers/consent.js
  app/controllers/uploadedFile.js
  app/lib/my-http-wrapper/http/Application.js
  app/snip.js
  app/templates/error.js
  app/templates/mainTemplate.js
Labels: enhancement

#405 fix(perf): Close MongoDB cursors after calling forEach2()
  app/controllers/admin/db.js
  app/controllers/api/track.js
  app/models/deezer.js
  app/models/mongodb.js
  app/models/notif.js
  app/models/post.js
  app/models/track.js
Labels: enhancement

#406 fix(tests): Track test coverage data using nyc
  .dockerignore
  .github/workflows/nodejs.yml
  .gitignore
  app/lib/my-http-wrapper/http/Application.js
  cypress/plugins/index.ts
  cypress/support/index.ts
  docker-compose.yml
  package-lock.json
  package.json
Labels: enhancement

#407 feat(facebook): Remove calls to Facebook Opengraph
  app/models/user.js
  app/templates/settings.html
  public/js/facebook.js
  public/js/postBox.js
  public/js/postBoxV2.js
  public/js/settings.js
  public/js/whyd.js
  public/js/whydPlayer.js
Labels: enhancement

#408 fix(bookmarklet): Remove PlayemJS from bookmarklet
  public/js/bookmarkletUI.ts
Labels: enhancement

#409 feat(onboarding): Simplify onboarding process
  app/controllers/onboarding.js
  app/controllers/private/register.js
  app/controllers/userLibrary.js
  app/models/featuredUsers.js
  app/templates/feed.html
  app/templates/onboarding.html
  app/templates/onboarding/bookmarklet-old.html
  app/templates/onboarding/bookmarklet.html
  app/templates/onboarding/pickPeople.html
  config/app.route
  cypress/integration/acceptance.spec.ts
  docker-compose.yml
  docs/API.md
  public/css/browse.css
  public/css/common.css
  public/css/onboarding.css
  public/html/dlgWelcome.html
  public/images/OnboardingIconTipModal.png
  public/images/addFirstTrack.png
  public/images/addFromUser.png
  public/images/addFromUser2.png
  public/images/btn-add-to-my-library.png
  public/images/btn-jumpin-email.jpg
  public/images/btn-jumpin.png
  public/images/btn-onb-jumpin.png
  public/images/clickanddrag.jpg
  public/images/help/arrow-right-onboarding.png
  public/images/icon-add-small.png
  public/images/pickBookmarklet/background.jpg
  public/images/pickBookmarklet/icon-navigateur.png
  public/images/pickBookmarklet/icon-puce.png
  public/images/pickBookmarklet/logo-mp3.png
  public/images/pickBookmarklet/logo-soundcloud.png
  public/images/pickBookmarklet/logo-vimeo.png
  public/images/pickBookmarklet/logo-youtube.png
  public/images/pickBookmarklet/puce-drag.png
  public/images/pickBookmarklet/separation.png
  public/images/pickBookmarklet/video-play-big.png
  public/images/pickBookmarklet/video-thumb.jpg
  public/images/video-play.png
  public/js/onboarding.js
  public/js/whyd.js
  test/api/user.api.tests.js
Labels: enhancement

#412 fix(debug): Track front-end errors with Datadog RUM
  app/templates/mainTemplate.js
Labels: production

#415 fix: sort playlist feature bug
  public/js/whyd.js
Labels: bug
