Repository openwhyd/openwhyd, pull requests merged in 2021-05, with the labels that each got.

#438 docs: Add TODOs
  app/controllers/LibUser.js
  app/controllers/api/postEdit.js
  public/js/bookmarklet.js
Labels: enhancement

#449 fix: Upgrade Node.js from v12.19.1 to v14.16.1 (LTS)
  .circleci/config.yml
  .github/workflows/ci.yml
  .nvmrc
  .vscode/launch.json
  Dockerfile
  package.json
Labels: enhancement

#450 fix(security): Remove unsafe redirect
  public/html/redirect.html
Labels: security / privacy

#454 fix(fb): Update Facebook login SDK
  app/models/facebook.js
  app/models/mongodb-shell-runner.js
  app/models/mongodb.js
  app/templates/mainTemplate.js
  config/initdb_testing.js
  cypress/fixtures/users.js
  public/html/testFbInvite.html
  public/js/facebook.js
Labels: enhancement

#455 fix(docker): Apply OWASP recommendations
  .dockerignore
  .github/workflows/ci.yml
  Dockerfile
  app.js
  app/lib/my-http-wrapper/http/Application.js
  app/models/analytics.js
  docker-compose.yml
Labels: enhancement, production, security / privacy

#460 fix(#458): Support Deezer track URLs with a locale/country prefix
  app/models/config.js
  docs/playemjs-fix-procedure.md
  package-lock.json
  package.json
  public/js/playem-all.js
  public/js/playem-min.js
Labels: enhancement

#461 fix(ui): Paste a YouTube / Soundcloud / Bandcamp / Deezer / MP3 track URL here
  app/templates/mainTemplate.js
  public/css/common.css
  public/css/userProfileV2.css
  public/images/plus-add-track-from-search.png
Labels: enhancement
